In [242]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [243]:
# 파일 불러오기
dataset = pd.read_excel('data_45.xlsx')

# 필요없는 컬럼 drop
dataset = dataset.drop('cust', axis = 1)

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

dataset
# label이 고객의 이탈과 유지를 확인하는 레이블

ma_fem_dv   A01   A02   A03  A04   A05   A06  B01   C01   C02   D01  \
0             1  0.25  0.00  0.00  0.0  0.00  0.50  0.0  0.00  0.00  0.25   
1             1  0.36  0.02  0.00  0.0  0.00  0.00  0.0  0.05  0.00  0.10   
2             1  0.05  0.00  0.00  0.0  0.00  0.43  0.0  0.00  0.00  0.00   
3             0  0.00  1.00  0.00  0.0  0.00  0.00  0.0  0.00  0.00  0.00   
4             1  0.20  0.00  0.00  0.0  0.00  0.00  0.0  0.60  0.00  0.00   
...         ...   ...   ...   ...  ...   ...   ...  ...   ...   ...   ...   
8901          1  0.00  0.00  0.00  0.0  0.00  0.00  0.0  0.00  0.00  0.00   
8902          1  0.00  0.00  0.00  0.0  0.03  0.03  0.0  0.00  0.00  0.03   
8903          1  0.00  0.00  0.00  0.0  0.00  0.01  0.0  0.00  0.00  0.00   
8904          1  0.14  0.05  0.03  0.7  0.00  0.03  0.0  0.00  0.00  0.00   
8905          1  0.38  0.06  0.06  0.0  0.00  0.38  0.0  0.00  0.06  0.00   

       D02  E01   L00   L01  오프라인   온라인  count_days  label  
0     0.00  0.0  0.00  0.00  0.25  0.75           4      0  
1     0.00  0.0  0.02  0.45  0.38  0.62          30      1  
2     0.00  0.0  0.01  0.51  0.06  0.94          75      1  
3     0.00  0.0  0.00  0.00  1.00  0.00          37      0  
4     0.20  0.0  0.00  0.00  0.80  0.20           3      0  
...    ...  ...   ...   ...   ...   ...         ...    ...  
8901  0.00  1.0  0.00  0.00  0.00  1.00           2      1  
8902  0.00  0.0  0.37  0.53  0.03  0.97          23      0  
8903  0.00  0.0  0.01  0.97  0.00  1.00          67      1  
8904  0.01  0.0  0.05  0.00  0.94  0.06          67      0  
8905  0.00  0.0  0.06  0.00  0.56  0.44          15      0  

[8906 rows x 19 columns]

In [244]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [245]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

c:\Users\ASIA-08\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

분류 결과 예측 (테스트 세트)

In [246]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [247]:
Y = pd.DataFrame(y_pred)
Y.to_csv("이탈고객 예측 값.csv")

In [248]:
y_test

array([1, 0, 1, ..., 0, 1, 0], dtype=int64)

In [249]:
model.score(X_test, y_test)

0.6919910179640718

In [250]:
confusion_matrix(y_test, y_pred)

array([[1132,  217],
       [ 606,  717]], dtype=int64)